name: Paul Kunze
author: Paul Kunze
baseurl: http://pkunze.github.io/
description: Je sch채rfer die Klinge, desto sch채rfer der Schnitt
github: http://www.github.com/pkunze
twitter: http://www.twitter.com/iamdabei
facebook: http://www.facebook.com/paulkunze1
email: pkunze[at]hotmail.de
location: 42째2'16"N   70째12'47"W
disqus: paulkunze

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
