name: Paul Kunze
author: Paul Kunze
baseurl: http://pkunze.github.io
description: Developer - Dresden, GER
github: http://www.github.com/pkunze
twitter: http://www.twitter.com/iamdabei
stackoverflow: http://stackoverflow.com/users/1776367/nozzleman
email: pkunze[at]hotmail.de
location: 51°0'47"N   13°43'51"W
disqus: paulkunzegithub

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
