# Site settings
title: This is my pretty face
email: your-email@domain.com
description: "I am a software developer from Dresden, Germany with a strong insterest in .NET, Laravel and good code in general."
baseurl: ""
url: "http://pkunze.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Add custom collections
collections:
  work:
    output: false

# Set defaults
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      author: "Stanley Stinson"
      date: ""
      title: ""
      category: ""
      tags: ""
